the3:
	gcc -ansi -Wall -pedantic-errors the3.c main.c -lm -o the3
adding_main1:
	gcc -ansi -Wall -pedantic-errors the3.c samples/adding_main1.c -lm -o adding_main1
adding_main2:
	gcc -ansi -Wall -pedantic-errors the3.c samples/adding_main2.c -lm -o adding_main2
print_main1:
	gcc -ansi -Wall -pedantic-errors the3.c samples/print_main1.c -lm -o print_main1
print_main2:
	gcc -ansi -Wall -pedantic-errors the3.c samples/print_main2.c -lm -o print_main2
place_main1:
	gcc -ansi -Wall -pedantic-errors the3.c samples/place_main1.c -lm -o place_main1
place_main2:
	gcc -ansi -Wall -pedantic-errors the3.c samples/place_main2.c -lm -o place_main2
serve_main1:
	gcc -ansi -Wall -pedantic-errors the3.c samples/serve_main1.c -lm -o serve_main1
serve_main2:
	gcc -ansi -Wall -pedantic-errors the3.c samples/serve_main2.c -lm -o serve_main2
remove_main1:
	gcc -ansi -Wall -pedantic-errors the3.c samples/remove_main1.c -lm -o remove_main1
remove_main2:
	gcc -ansi -Wall -pedantic-errors the3.c samples/remove_main2.c -lm -o remove_main2