the1:
	gcc -ansi -Wall -pedantic-errors the1.c main.c -lm -o the1 
init:
	gcc -ansi -Wall -pedantic-errors the1.c samples/init_main.c -lm -o the1_init
insert:
	gcc -ansi -Wall -pedantic-errors the1.c samples/insert_main.c -lm -o the1_insert	
delete:
	gcc -ansi -Wall -pedantic-errors the1.c samples/delete_main.c -lm -o the1_delete
draw:
	gcc -ansi -Wall -pedantic-errors the1.c samples/draw_main.c -lm -o the1_draw
height:
	gcc -ansi -Wall -pedantic-errors the1.c samples/height_main.c -lm -o the1_height
min:
	gcc -ansi -Wall -pedantic-errors the1.c samples/min_main.c -lm -o the1_min
breadth:
	gcc -ansi -Wall -pedantic-errors the1.c samples/breadth_main.c -lm -o the1_breadth
depth:
	gcc -ansi -Wall -pedantic-errors the1.c samples/depth_main.c -lm -o the1_depth
complex:
	gcc -ansi -Wall -pedantic-errors the1.c samples/complex_main.c -lm -o the1_complex	
