the2:
	gcc -ansi -Wall -pedantic-errors the2.c main.c -lm -o the2
init:
	gcc -ansi -Wall -pedantic-errors the2.c samples/init_main.c -lm -o init_main
print1:
	gcc -ansi -Wall -pedantic-errors the2.c samples/print1_main.c -lm -o print1_main
print2:
	gcc -ansi -Wall -pedantic-errors the2.c samples/print2_main.c -lm -o print2_main
dot1:
	gcc -ansi -Wall -pedantic-errors the2.c samples/dot1_main.c -lm -o dot1_main
dot2:
	gcc -ansi -Wall -pedantic-errors the2.c samples/dot2_main.c -lm -o dot2_main
covariance1:
	gcc -ansi -Wall -pedantic-errors the2.c samples/covariance1_main.c -lm -o covariance1_main
xtx1:
	gcc -ansi -Wall -pedantic-errors the2.c samples/xtx1_main.c -lm -o xtx1_main
group1:
	gcc -ansi -Wall -pedantic-errors the2.c samples/group1_main.c -lm -o group1_main
group2:
	gcc -ansi -Wall -pedantic-errors the2.c samples/group2_main.c -lm -o group2_main
group3:
	gcc -ansi -Wall -pedantic-errors the2.c samples/group3_main.c -lm -o group3_main
group4:
	gcc -ansi -Wall -pedantic-errors the2.c samples/group4_main.c -lm -o group4_main
conv1:
	gcc -ansi -Wall -pedantic-errors the2.c samples/conv1_main.c -lm -o conv1_main
conv2:
	gcc -ansi -Wall -pedantic-errors the2.c samples/conv2_main.c -lm -o conv2_main